apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo
spec:
  project: default

  source:
    repoURL: https://github.com/12brandao/gitops-project
    targetRevision: HEAD
    path: app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
